-- HR Analytics Database Design
-- Creates star schema with 4 tables and loads 17,414 employee records
-- Includes 10 analysis queries for employee performance insights

create database HR_ANALYTICS

USE HR_ANALYTICS

CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT PRIMARY KEY,
	GENDER VARCHAR(50),
	AGE INT,
	EDUCATION VARCHAR(50),
	RECRUITMENT_CHANNEL VARCHAR(50),
	LENGTH_OF_SERVICE INT
);

CREATE TABLE DEPARTMENTS(
	DEPARTMENT_ID INT PRIMARY KEY,
	DEPARTMENT VARCHAR(50)
);

CREATE TABLE REGIONS(
	REGION_ID INT PRIMARY KEY,
	REGION VARCHAR(50)
);

CREATE TABLE FACT_TABLE(
	FACT_ID INT PRIMARY KEY,
	EMPLOYEE_ID INT,
	DEPARTMENT_ID INT,
	REGION_ID INT,
	KPIS_MET_MORE_THAN_80 INT,
	AWARDS_WON INT,
	AVG_TRAINING_SCORE FLOAT,
	PREVIOUS_YEAR_RATING FLOAT,
	NO_OF_TRAININGS INT,
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
	FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

BULK INSERT DEPARTMENTS
FROM 'C:\Final Project Pixels\data cleaned\departments.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',
    TABLOCK
);

BULK INSERT REGIONS
FROM 'C:\Final Project Pixels\data cleaned\regions.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',
    TABLOCK
);

BULK INSERT EMPLOYEES
FROM 'C:\Final Project Pixels\data cleaned\employees.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',
    TABLOCK
);

BULK INSERT FACT_TABLE
FROM 'C:\Final Project Pixels\data cleaned\fact.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',
    TABLOCK
);

SELECT COUNT(*) AS DEPARTMENTS_COUNT FROM DEPARTMENTS;  
SELECT COUNT(*) AS REGIONS_COUNT     FROM REGIONS;      
SELECT COUNT(*) AS EMPLOYEES_COUNT   FROM EMPLOYEES;    
SELECT COUNT(*) AS FACT_COUNT        FROM FACT_TABLE;

ALTER TABLE FACT_TABLE
ALTER COLUMN AVG_TRAINING_SCORE DECIMAL(5, 2);


SELECT D.DEPARTMENT, AVG(F.AVG_TRAINING_SCORE) AS AVG_TRAINING_SCORE
FROM FACT_TABLE F
JOIN DEPARTMENTS D ON F.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT
ORDER BY AVG_TRAINING_SCORE DESC;

SELECT D.DEPARTMENT, AVG(CAST(F.KPIS_MET_MORE_THAN_80 AS FLOAT)) AS KPI_RATE
FROM FACT_TABLE F
JOIN DEPARTMENTS D ON F.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT
ORDER BY KPI_RATE DESC;

SELECT D.DEPARTMENT, SUM(F.AWARDS_WON) AS TOTAL_AWARDS
FROM FACT_TABLE F
JOIN DEPARTMENTS D ON F.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT
ORDER BY TOTAL_AWARDS DESC;

SELECT E.EDUCATION, AVG(F.AVG_TRAINING_SCORE) AS AVG_TRAINING_SCORE
FROM FACT_TABLE F
JOIN EMPLOYEES E ON F.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY E.EDUCATION
ORDER BY AVG_TRAINING_SCORE DESC;

SELECT E.GENDER, AVG(CAST(F.KPIS_MET_MORE_THAN_80 AS FLOAT)) AS KPI_RATE
FROM FACT_TABLE F
JOIN EMPLOYEES E ON F.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY E.GENDER
ORDER BY KPI_RATE DESC;

SELECT E.RECRUITMENT_CHANNEL, AVG(F.PREVIOUS_YEAR_RATING) AS AVG_RATING
FROM FACT_TABLE F
JOIN EMPLOYEES E ON F.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY E.RECRUITMENT_CHANNEL
ORDER BY AVG_RATING DESC;

SELECT F.NO_OF_TRAININGS, AVG(CAST(F.KPIS_MET_MORE_THAN_80 AS FLOAT)) AS KPI_RATE
FROM FACT_TABLE F
GROUP BY F.NO_OF_TRAININGS
ORDER BY F.NO_OF_TRAININGS;

SELECT F.NO_OF_TRAININGS, AVG(F.AVG_TRAINING_SCORE) AS AVG_TRAINING_SCORE
FROM FACT_TABLE F
GROUP BY F.NO_OF_TRAININGS
ORDER BY F.NO_OF_TRAININGS;

SELECT R.REGION, COUNT(F.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM FACT_TABLE F
JOIN REGIONS R ON F.REGION_ID = R.REGION_ID
GROUP BY R.REGION
ORDER BY EMPLOYEE_COUNT DESC;

SELECT F.PREVIOUS_YEAR_RATING, AVG(CAST(F.AWARDS_WON AS FLOAT)) AS AWARD_RATE
FROM FACT_TABLE F
GROUP BY F.PREVIOUS_YEAR_RATING
ORDER BY F.PREVIOUS_YEAR_RATING;